export type Theme = "dark" | "light";

export const darkVars = {
  "--color-bg":              "#0A0A0F",
  "--color-surface":         "#16161F",
  "--color-elevated":        "#1E1E2E",
  "--color-overlay":         "#252535",
  "--color-border":          "#2A2A3E",
  "--color-border-hover":    "#3A3A5C",
  "--color-accent":          "#7C3AED",
  "--color-accent-hover":    "#8B5CF6",
  "--color-cyan":            "#22D3EE",
  "--color-text":            "#F1F0FF",
  "--color-text-sub":        "#9B9BC0",
  "--color-text-muted":      "#5C5C7A",
  "--color-ai-bubble":       "#1E1E2E",
  "--color-ai-bubble-border":"#2A2A3E",
  "--color-sidebar":         "#111118",
  "--color-input-bg":        "#1E1E2E",
  "--color-hover-bg":        "rgba(255, 255, 255, 0.06)",
  "--color-hover-bg-strong": "rgba(255, 255, 255, 0.1)",
  "--color-subtle-border":   "rgba(255, 255, 255, 0.08)",
  "--color-card-bg":         "rgba(255, 255, 255, 0.03)",
  "--color-card-border":     "rgba(255, 255, 255, 0.08)",
  "--color-divider":         "rgba(255, 255, 255, 0.06)",
  "--color-placeholder":     "#5C5C7A",
  "--color-icon":            "#9B9BC0",
  "--color-icon-hover":      "#F1F0FF",
  "--color-disabled":        "#5C5C7A",
  "--color-avatar":          "linear-gradient(135deg, #7C3AED, #22D3EE)",
  "--color-scrollbar-thumb": "#2A2A3E",
  "--color-scrollbar-hover": "#3A3A5C",
  "--shadow-glow":           "0 0 20px rgba(124,58,237,0.4)",
} as const;

export const lightVars = {
  "--color-bg":              "#F5F4FF",
  "--color-surface":         "#FFFFFF",
  "--color-elevated":        "#EEF0FF",
  "--color-overlay":         "#E6E8FF",
  "--color-border":          "#D4D0F0",
  "--color-border-hover":    "#B8B2E8",
  "--color-accent":          "#7C3AED",
  "--color-accent-hover":    "#6D28D9",
  "--color-cyan":            "#0891B2",
  "--color-text":            "#0A0A1A",
  "--color-text-sub":        "#3D3B5C",
  "--color-text-muted":      "#6B6989",
  "--color-ai-bubble":       "#FFFFFF",
  "--color-ai-bubble-border":"#D4D0F0",
  "--color-sidebar":         "#FFFFFF",
  "--color-input-bg":        "#FFFFFF",
  "--color-hover-bg":        "rgba(0, 0, 0, 0.04)",
  "--color-hover-bg-strong": "rgba(0, 0, 0, 0.07)",
  "--color-subtle-border":   "rgba(0, 0, 0, 0.1)",
  "--color-card-bg":         "#FFFFFF",
  "--color-card-border":     "rgba(0, 0, 0, 0.08)",
  "--color-divider":         "rgba(0, 0, 0, 0.08)",
  "--color-placeholder":     "#8A88AA",
  "--color-icon":            "#4A4870",
  "--color-icon-hover":      "#0A0A1A",
  "--color-disabled":        "#B8B2E8",
  "--color-avatar":          "linear-gradient(135deg, #7C3AED, #22D3EE)",
  "--color-scrollbar-thumb": "#D4D0F0",
  "--color-scrollbar-hover": "#B8B2E8",
  "--shadow-glow":           "0 0 20px rgba(124,58,237,0.25)",
} as const;
